### ISSUE TITLE
Plugin outdated(?)

### ISSUE THREAD

**Issue by Freso** [phw/discourse-musicbrainz-onebox#10]
It seems like no entities get any onebox at all anymore. The Jira onebox plugin has also stopped working, so I'm thinking something changed in upstream Discourse (but I didn't look into what).

**Comment by phw** [comment]
Ok, I should be able to have a look at this during next week. Maybe I can even tackle some of the open issues while I'm at it. Can you take a look at the MB Discourse installation and see if there is anything in the logs?
